
// import { useEffect, useState } from "react";
// import { jsPDF } from "jspdf";

// function MyRequests(){

//   const [requests,setRequests] = useState([]);
//   const user = JSON.parse(localStorage.getItem("user"));

//   useEffect(()=>{
//     fetch(`http://localhost:8081/web-project/web-project-php/backend/index.php?action=requests&student_id=${user.id}`)
//       .then(res=>res.json())
//       .then(data=>{
//         if(Array.isArray(data)) setRequests(data);
//         else setRequests([]);
//       })
//       .catch(()=>setRequests([]));
//   },[]);

//   // 🎓 PROFESSIONAL CERTIFICATE PDF
//   const downloadPDF = (r) => {

//     const doc = new jsPDF();

//     // BORDER
//     doc.setDrawColor(0);
//     doc.rect(5,5,200,287);

//     // HEADER
//     doc.setFont("times","bold");
//     doc.setFontSize(20);
//     doc.text("ADAMA SCIENCE AND TECHNOLOGY UNIVERSITY", 105, 25, { align:"center" });

//     doc.setFontSize(16);
//     doc.text("OFFICIAL CLEARANCE CERTIFICATE", 105, 35, { align:"center" });

//     // LINE
//     doc.line(20,40,190,40);

//     // BODY
//     doc.setFont("times","normal");
//     doc.setFontSize(12);

//     doc.text(`This is to certify that:`, 20, 60);

//     doc.setFont("times","bold");
//     doc.text(`${user.name}`, 20, 70);

//     doc.setFont("times","normal");
//     doc.text(`has successfully completed all clearance requirements.`, 20, 80);

//     doc.text(`Request ID: ${r.id}`, 20, 100);
//     doc.text(`Status: COMPLETED`, 20, 110);

//     doc.text(`All university departments have approved this clearance.`, 20, 130);

//     // SIGNATURE AREA
//     doc.line(20, 200, 80, 200);
//     doc.text("Registrar Signature", 20, 210);

//     doc.line(120, 200, 180, 200);
//     doc.text("Official Stamp", 120, 210);

//     // FOOTER
//     doc.setFontSize(10);
//     doc.text(`Verification Code: ASTU-${r.id}`, 20, 260);
//     doc.text(`Generated by ASTU Clearance System`, 105, 270, { align:"center" });

//     doc.save(`ASTU_Clearance_${r.id}.pdf`);
//   };

//   return (
//     <div style={styles.page}>

//       <div style={styles.container}>
//         <h1 style={styles.title}>My Clearance Requests</h1>

//         {requests.length === 0 && (
//           <div style={styles.empty}>No requests found</div>
//         )}

//         {requests.map(r=>{

//           const approved = Number(r.approved)||0;
//           const total = Number(r.total)||0;
//           const progress = total>0 ? (approved/total)*100 : 0;
//           const completed = total>0 && approved===total;

//           return (
//             <div key={r.id} style={styles.card}>

//               <div style={styles.top}>
//                 <div>
//                   <h3>Request #{r.id}</h3>
//                   <p style={styles.sub}>Clearance Progress</p>
//                 </div>

//                 <span style={{
//                   ...styles.badge,
//                   background: completed ? "#16a34a" : "#f59e0b"
//                 }}>
//                   {completed ? "Completed" : "Pending"}
//                 </span>
//               </div>

//               <div style={styles.progressBox}>
//                 <div style={styles.progressBar}>
//                   <div style={{
//                     ...styles.progressFill,
//                     width:`${progress}%`
//                   }}></div>
//                 </div>

//                 <p style={styles.progressText}>
//                   {approved} / {total} Approved
//                 </p>
//               </div>

//               {completed && (
//                 <button
//                   style={styles.download}
//                   onClick={()=>downloadPDF(r)}
//                 >
//                   Download Official Certificate
//                 </button>
//               )}

//             </div>
//           );
//         })}

//         <button style={styles.back} onClick={()=>window.location.href="/student"}>
//           Back to Dashboard
//         </button>
//       </div>

//     </div>
//   );
// }

// const styles = {

//   page:{
//     minHeight:"100vh",
//     background:"#eef2f7",
//     display:"flex",
//     justifyContent:"center",
//     padding:"40px"
//   },

//   container:{
//     width:"600px"
//   },

//   title:{
//     textAlign:"center",
//     marginBottom:"30px",
//     fontWeight:"bold"
//   },

//   empty:{
//     textAlign:"center",
//     color:"#777"
//   },

//   card:{
//     background:"#fff",
//     padding:"20px",
//     borderRadius:"12px",
//     marginBottom:"20px",
//     boxShadow:"0 6px 15px rgba(0,0,0,0.05)"
//   },

//   top:{
//     display:"flex",
//     justifyContent:"space-between",
//     alignItems:"center"
//   },

//   sub:{
//     fontSize:"12px",
//     color:"#777"
//   },

//   badge:{
//     color:"#fff",
//     padding:"5px 12px",
//     borderRadius:"20px",
//     fontSize:"12px"
//   },

//   progressBox:{
//     marginTop:"15px"
//   },

//   progressBar:{
//     height:"10px",
//     background:"#ddd",
//     borderRadius:"10px"
//   },

//   progressFill:{
//     height:"100%",
//     background:"#2563eb",
//     borderRadius:"10px"
//   },

//   progressText:{
//     marginTop:"5px",
//     fontSize:"12px"
//   },

//   download:{
//     marginTop:"15px",
//     padding:"12px",
//     width:"100%",
//     background:"#16a34a",
//     color:"#fff",
//     border:"none",
//     borderRadius:"8px",
//     cursor:"pointer",
//     fontWeight:"bold"
//   },

//   back:{
//     marginTop:"20px",
//     padding:"12px",
//     width:"100%",
//     background:"#333",
//     color:"#fff",
//     border:"none",
//     borderRadius:"8px",
//     cursor:"pointer"
//   }
// };

// export default MyRequests;

import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";

function MyRequests(){

  const [requests,setRequests] = useState([]);
  const user = JSON.parse(localStorage.getItem("user"));

  useEffect(()=>{

    fetch(`http://localhost:8081/web-project/web-project-php/backend/index.php?action=requests&student_id=${user.id}`)
      .then(res=>res.json())
      .then(data=>{
        if(Array.isArray(data)) setRequests(data);
        else setRequests([]);
      });

  },[]);
  const downloadPDF = (r) => {

    const doc = new jsPDF();

    // BORDER
    doc.setDrawColor(0);
    doc.rect(5,5,200,287);

    // HEADER
    doc.setFont("times","bold");
    doc.setFontSize(20);
    doc.text("ADAMA SCIENCE AND TECHNOLOGY UNIVERSITY", 105, 25, { align:"center" });

    doc.setFontSize(16);
    doc.text("OFFICIAL CLEARANCE CERTIFICATE", 105, 35, { align:"center" });

    // LINE
    doc.line(20,40,190,40);

    // BODY
    doc.setFont("times","normal");
    doc.setFontSize(12);

    doc.text(`This is to certify that:`, 20, 60);

    doc.setFont("times","bold");
    doc.text(`${user.name}`, 20, 70);

    doc.setFont("times","normal");
    doc.text(`has successfully completed all clearance requirements.`, 20, 80);

    doc.text(`Request ID: ${r.id}`, 20, 100);
    doc.text(`Status: COMPLETED`, 20, 110);

    doc.text(`All university departments have approved this clearance.`, 20, 130);

    // SIGNATURE AREA
    doc.line(20, 200, 80, 200);
    doc.text("Registrar Signature", 20, 210);

    doc.line(120, 200, 180, 200);
    doc.text("Official Stamp", 120, 210);

    // FOOTER
    doc.setFontSize(10);
    doc.text(`Verification Code: ASTU-${r.id}`, 20, 260);
    doc.text(`Generated by ASTU Clearance System`, 105, 270, { align:"center" });

    doc.save(`ASTU_Clearance_${r.id}.pdf`);
  };
  

  return (
    <div style={styles.page}>

      <div style={styles.container}>

        <h2 style={styles.title}>My Clearance Requests</h2>

        {requests.length === 0 && (
          <p style={styles.empty}>No requests found</p>
        )}

        {requests.map(r=>{

          const approved = Number(r.approved || 0);
          const total = Number(r.total || 0);

          const progress = total === 0 ? 0 : (approved / total) * 100;
          const completed = total > 0 && approved === total;

          return (
            <div key={r.id} style={styles.card}>

              {/* HEADER */}
              <div style={styles.header}>
                <h3>Request #{r.id}</h3>

                <span style={{
                  ...styles.badge,
                  background: completed ? "#16a34a" : "#f59e0b"
                }}>
                  {completed ? "Approved" : "Pending"}
                </span>
              </div>

              {/* PROGRESS BAR (FIXED) */}
              <div style={styles.barWrap}>
                <div style={styles.bar}>
                  <div style={{
                    ...styles.fill,
                    width: `${progress}%`
                  }}></div>
                </div>

                <p style={styles.text}>
                  {approved} / {total} Approved
                </p>
              </div>

              {/* DEPARTMENTS */}
              <div style={styles.box}>
                {r.departments?.map((d,i)=>(
                  <div key={i} style={styles.row}>
                    <span>{d.name}</span>

                    <span style={{
                      ...styles.smallBadge,
                      background:
                        d.status === "approved" ? "#16a34a" :
                        d.status === "rejected" ? "#dc2626" :
                        "#f59e0b"
                    }}>
                      {d.status}
                    </span>
                  </div>
                ))}
              </div>

              {/* DOWNLOAD */}
              {completed && (
                <button style={styles.btn} onClick={()=>downloadPDF(r)}>
                  Download Certificate
                </button>
              )}

            </div>
          );
        })}

      </div>

    </div>
  );
}

const styles = {

  page:{
    minHeight:"100vh",
    background:"#eef2f7",
    display:"flex",
    justifyContent:"center",
    padding:"40px",
    fontFamily:"Arial"
  },

  container:{
    width:"600px"
  },

  title:{
    textAlign:"center",
    marginBottom:"20px"
  },

  empty:{
    textAlign:"center",
    color:"#777"
  },

  card:{
    background:"#fff",
    padding:"18px",
    borderRadius:"12px",
    marginBottom:"15px",
    boxShadow:"0 5px 12px rgba(0,0,0,0.08)"
  },

  header:{
    display:"flex",
    justifyContent:"space-between",
    alignItems:"center"
  },

  badge:{
    color:"#fff",
    padding:"5px 12px",
    borderRadius:"20px",
    fontSize:"12px"
  },

  barWrap:{
    marginTop:"12px"
  },

  bar:{
    height:"10px",
    background:"#ddd",
    borderRadius:"10px",
    overflow:"hidden"
  },

  fill:{
    height:"100%",
    background:"#2563eb"
  },

  text:{
    fontSize:"12px",
    marginTop:"5px"
  },

  box:{
    marginTop:"12px",
    background:"#f8fafc",
    padding:"10px",
    borderRadius:"8px"
  },

  row:{
    display:"flex",
    justifyContent:"space-between",
    padding:"5px 0",
    borderBottom:"1px solid #eee"
  },

  smallBadge:{
    color:"#fff",
    fontSize:"11px",
    padding:"3px 8px",
    borderRadius:"10px"
  },

  btn:{
    marginTop:"12px",
    width:"100%",
    padding:"10px",
    background:"#16a34a",
    color:"#fff",
    border:"none",
    borderRadius:"8px",
    cursor:"pointer"
  }
};

export default MyRequests;